export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const GET_PATIENT = 'GET_PATIENT';
export const UPDATE_PATIENT='UPDATE_PATIENT';


export const GET_APPOINTMENT='GET_APPOINTMENT';
export const UPDATE_APPOINTMENT='UPDATE_APPOINTMENT';

export const GET_CONSULTATIONS='GET_CONSULTATIONS';
